openapi: 3.1.0
x-stoplight:
  id: wyjb3inenb3rt
info:
  title: ProjectMS API
  version: '1.0'
  description: Server API for Company-oriented projects management application
servers:
  - url: 'http://localhost:3000'
    description: ''
paths:
  /students:
    get:
      summary: Get all students
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-10-23'
                    statusCode: 200
                    httpStatus: ok
                    message: Students fetched successfully
                    data:
                      - student_id: 1
                        student_name: John doe
                        email: john@mail.com
                        class_code: din22sp
                        created_at: '2024-10-02'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-05-24'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while fetching students
      operationId: get-students
      x-stoplight:
        id: em5ha0rt2ds7c
      description: Get all students from students table
    post:
      summary: Create new student
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 201
                    httpStatus: CREATED
                    message: Student created successfully
                    data:
                      student_id: 1
                      student_name: John doe
                      email: john@mail.com
                      class_code: din22sp
                      created_at: '2024-10-02'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while creating new student
      operationId: post-students
      x-stoplight:
        id: 9dhjiveekb7ry
      description: Add new student to students table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Student_new'
            examples:
              Example 1:
                value:
                  student_name: Jane Doe
                  email: jane@gmail.com
                  class_code: undefined
  '/students/{student_id}':
    parameters:
      - schema:
          type: string
        name: student_id
        in: path
        required: true
        description: ID of the student handled
    put:
      summary: Update student
      operationId: patch-students-userId
      responses:
        '200':
          description: User class code updated successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 200
                    httpStatus: OK
                    message: Student updated
                    data:
                      student_id: 1
                      student_name: John doe
                      email: john@mail.com
                      class_code: din22sp
                      created_at: '2024-10-02'
        '404':
          description: User Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Student not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while updating student
      description: Update data of a selected student
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Student'
            examples:
              Example 1:
                value:
                  student_id: 142
                  student_name: Alice Smith
                  email: alice.smith@gmail.com
                  class_code: din21sp
                  created_at: '2024-10-23'
        description: Patch user properties to update.
      x-stoplight:
        id: ni8wgrou4ocu5
      parameters:
        - schema:
            type: number
          in: query
          name: student_id
          description: ID of the student modified
  '/students/{email}':
    parameters:
      - schema:
          type: string
        name: email
        in: path
        required: true
        description: Email of the student handled
    get:
      summary: Get student
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 200
                    httpStatus: ok
                    message: Student fetched successfully
                    data:
                      - student_id: 1
                        student_name: John doe
                        email: john@mail.com
                        class_code: din22sp
                        created_at: '2024-10-02'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Student not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while fetching students
      operationId: get-student-email
      x-stoplight:
        id: gsj3hpt6vbdkv
      description: Get a student from students table selected by student email
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: Student email obtained from ID token
          required: true
  /projects:
    get:
      summary: Get all projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Projects fetched successfully
                    data:
                      - {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching projects
      operationId: get-projects
      x-stoplight:
        id: t5wavhpaz2j51
      description: Get a list of all projects in projects table
    post:
      summary: Create new project
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 201
                    httpStatus: CREATED
                    message: New project created successfully
                    data:
                      student_id: 1
                      project_id: 1
                      project_name: My project
                      project_desc: Project description
                      teacher_id: 3
                      company_id: 6
                      project_status: pending
                      project_url: 'http://example.com'
                      start_date: '2019-08-24'
                      end_date: '2019-08-24'
                      created_at: '2019-08-24'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while creating project
      operationId: post-project
      x-stoplight:
        id: yyq1luuuqr7mb
      description: Add new project to projects table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Project_new'
            examples:
              Example 1:
                value:
                  project_id: 1
                  project_name: My project
                  project_desc: Project description
                  teacher_id: 3
                  company_id: 6
                  project_status: pending
                  project_url: 'http://example.com'
                  start_date: '2019-08-24'
                  end_date: '2019-08-24'
                  created_at: '2019-08-24'
    parameters: []
  '/projects/{project_id}':
    parameters:
      - schema:
          type: string
        name: project_id
        in: path
        required: true
        description: ID of the project handled
    put:
      summary: Update project
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    value:
                      time_stamp: string
                      statusCode: 200
                      httpStatus: OK
                      message: Project updated successfully
                      data:
                        project_id: 1
                        project_name: My project
                        project_desc: Project description
                        teacher_id: 3
                        company_id: 6
                        project_status: pending
                        project_url: 'http://example.com'
                        start_date: '2019-08-24'
                        end_date: '2019-08-24'
                        created_at: '2019-08-24'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while updating project
      operationId: put-projects-project_id
      x-stoplight:
        id: cdnaamv12yzfa
      description: Update data of a selected project
      parameters:
        - schema:
            type: number
          in: query
          name: project_id
          description: ID of the modified project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Project'
            examples:
              Example 1:
                value:
                  project_id: 1
                  project_name: My project
                  project_desc: Project description
                  teacher_id: 3
                  company_id: 6
                  project_status: pending
                  project_url: 'http://example.com'
                  start_date: '2019-08-24'
                  end_date: '2019-08-24'
                  created_at: '2019-08-24'
    delete:
      summary: Delete project
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Project deleted successfully
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Project not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while deleting project
      operationId: delete-projects-project_id
      x-stoplight:
        id: 8zl2d65w27f07
      description: Delete one project from projects tabe
      parameters:
        - schema:
            type: number
          in: query
          name: project_id
          description: ID of the deleted project
  /projects/student:
    get:
      summary: Get all student_projects
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Student projects fetched successfully
                    data:
                      - {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: No student_projects found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while fetching student projects
      operationId: get-student-projects
      description: Get a list of all student projects in student_project table
      x-stoplight:
        id: mke2w39rg70sq
    post:
      summary: Create new student_project
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Student project created successfully
                    data:
                      student_id: 1
                      project_id: 3
                      project_number: 2
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while creating student project
      operationId: post-student-project
      description: Add new student project to student_project table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - student_id
                - project_id
              properties:
                student_id:
                  type: number
                  x-stoplight:
                    id: 867fjs5nbwsn8
                project_id:
                  type: number
                  x-stoplight:
                    id: 0oy0n39apb7b6
            examples:
              Example 1:
                value:
                  student_id: 6
                  project_id: 4
      x-stoplight:
        id: fufdk2cadblgd
    parameters: []
  '/projects/{project_id}/notes':
    get:
      summary: Get all project notes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Project notes fetched successfully
                    data:
                      - {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: No student_projects found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2024-08-14'
                    statusCode: 500
                    httpStatus: INTERNAL_SERVER_ERROR
                    message: An error occurred while fetching project notes
      operationId: get-project-notes
      description: Get a list project notes in project_note table by project ID
      x-stoplight:
        id: mhmh71dgc9ooo
      parameters:
        - schema:
            type: number
          in: query
          name: project_id
          description: ID of the project
    parameters:
      - schema:
          type: string
        name: project_id
        in: path
        required: true
        description: Project ID of the notes handled
    post:
      summary: Create new note
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 201
                    httpStatus: CREATED
                    message: Project note added successfully
                    data:
                      note: Note text
                      document_path: path
                      created_by: Jane Doe
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while adding project note
      operationId: post-projects-project_id-notes
      x-stoplight:
        id: ws68er4nkdamz
      parameters:
        - schema:
            type: number
          in: query
          name: project_id
          description: ID of the project where note is added
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Note_new'
            examples:
              Example 1:
                value:
                  note: Note text
                  document_path: path
                  created_by: Jane Doe
      description: Add new note in project_note table
  '/projects/{project_id}/notes/{note_id}':
    parameters:
      - schema:
          type: string
        name: note_id
        in: path
        required: true
        description: ID of the note handled
      - schema:
          type: string
        name: project_id
        in: path
        required: true
        description: ID of the project handled
    delete:
      summary: Delete project note
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Note deleted successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while deleting note
      operationId: delete-projects-project_id-notes-note_id
      x-stoplight:
        id: faw61r1bzumcs
      parameters:
        - schema:
            type: number
          in: query
          name: project_id
          description: ID of the project
        - schema:
            type: number
          in: query
          name: note_id
          description: ID of the deleted note
      description: Delete all notes of a certain project
  /teachers:
    get:
      summary: Get all teachers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Teachers fetched successfully
                    data:
                      - {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching teachers
      operationId: get-teachers
      x-stoplight:
        id: rkcc4t0k1e9fr
      description: Get a list of all teachers in teachers table
    post:
      summary: Create new teacher
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 201
                    httpStatus: CREATED
                    message: Teacher created successfully
                    data:
                      teacher_id: 1
                      teacher_name: New Teacher
                      email: user@example.com
                      created_at: '2024-07-29'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while creating teacher
      operationId: post-teachers
      x-stoplight:
        id: xbt9ds9730b20
      description: Add new teacher to teachers table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Teacher_new'
            examples:
              Example 1:
                value:
                  teacher_name: New Teacher
                  email: user@example.com
  '/teachers/{email}':
    parameters:
      - schema:
          type: string
        name: email
        in: path
        required: true
        description: Email of the teacher
    get:
      summary: Get one teacher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Teacher fetched successfully
                    data:
                      teacher_id: 1
                      teacher_name: New Teacher
                      email: user@example.com
                      created_at: '2024-07-29'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Teacher not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching teacher
      operationId: get-teachers-email
      x-stoplight:
        id: utsov0g9qgnq1
      description: Get one teacher from teachers table by email
      requestBody:
        content: {}
      parameters:
        - schema:
            type: string
          in: query
          name: email
          description: Teacher email from ID token
  '/teachers/company/{company_name}':
    get:
      summary: Get teachers by company
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Teachers by company fetched successfully
                    data:
                      - {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Teachers by company not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching teachers
      operationId: get-teachers-company-company_name
      x-stoplight:
        id: w7pv6erpstb9p
      description: Get a list of teachers who have set a certain company as a favorite company
      parameters:
        - schema:
            type: string
          in: query
          name: company_name
          description: The name of the company with teacher's favority
    parameters:
      - schema:
          type: string
        name: company_name
        in: path
        required: true
        description: Name of the company related to teachers
  /companies:
    get:
      summary: Get all companies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Companies fetched successfully
                    data:
                      - {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching companies
      operationId: get-companies
      x-stoplight:
        id: 9cizzo3h5kk3p
      description: Get a list of all companies in companies table
    post:
      summary: Create new company
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 201
                    httpStatus: CREATED
                    message: Company created successfully
                    data:
                      company_id: 1
                      company_name: Nokia
                      created_at: '2024-10-16'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while creating company
      operationId: post-companies
      x-stoplight:
        id: erql8pr85wbkr
      description: Add new comapny to companies table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - company_name
              properties:
                company_name:
                  type: string
                  x-stoplight:
                    id: 2cttzgkr3fmlg
            examples:
              Example 1:
                value:
                  company_name: Nokia
  /companies/favo:
    post:
      summary: Create new company favo
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 201
                    httpStatus: CREATED
                    message: Favourite company added successfully
                    data:
                      company_id: 8
                      teacher_id: 5
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while adding favourite company
      operationId: post-companies-favo
      x-stoplight:
        id: hec2l2x8fqw0n
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                company_id:
                  type: number
                  x-stoplight:
                    id: bzlohveykd8xt
                teacher_id:
                  type: number
                  x-stoplight:
                    id: qm3539834ap5g
            examples:
              Example 1:
                value:
                  company_id: 8
                  teacher_id: 5
      description: Add new teacher's company favourite to company_teacher table
  '/companies/favo/{teacher_id}':
    get:
      summary: Get favo companies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 0
                    httpStatus: string
                    message: string
                    data:
                      - {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Favourite companies not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching favourite companies
      operationId: get-companies-favo-teacher_id
      x-stoplight:
        id: vkfqzl90b5wtn
      parameters:
        - schema:
            type: number
          in: query
          name: teacher_id
          description: ID of the teacher
      description: Get favourite companies of a certain teacher
    parameters:
      - schema:
          type: string
        name: teacher_id
        in: path
        required: true
        description: ID of the teacher
    delete:
      summary: Delete favo companies
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Favourite companies deleted successfully
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while deleting favourite company
      operationId: delete-companies-teacher_id
      x-stoplight:
        id: rpn1a2ncz79op
      parameters:
        - schema:
            type: number
          in: query
          name: teacher_id
          description: ID of the teacher
      description: Favourite company of a certain teacher is deleted
  /resources:
    get:
      summary: Get all resources
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Resources fetched successfully
                    data:
                      - {}
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while fetching resources
      operationId: get-resources
      x-stoplight:
        id: zxcmtxusdxh94
      description: Get a list of all resources in resources table
    post:
      summary: Create new resource
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 0
                    httpStatus: string
                    message: string
                    data:
                      resource_id: 4
                      teacher_id: 7
                      total_resources: 5
                      used_resources: 0
                      study_year: 2024-2025
                      created_at: '2024-10-25'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while creating resource
      operationId: post-resources
      x-stoplight:
        id: p696yh7itz56k
      description: Add new resource to resources table
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Resource_new'
            examples:
              Example 1:
                value:
                  teacher_id: 7
                  total_resources: 5
                  used_resources: 0
                  study_year: 2024-2025
  '/resources/{resource_id}':
    parameters:
      - schema:
          type: string
        name: resource_id
        in: path
        required: true
        description: ID of the resource handled
    put:
      summary: Update resource
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_object'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 200
                    httpStatus: OK
                    message: Resource updated successfully
                    data:
                      resource_id: 5
                      teacher_id: 7
                      total_resources: 5
                      used_resources: 1
                      study_year: 2024-2025
                      created_at: '2024-08-24'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 404
                    httpStatus: NOT FOUND
                    message: Resource not found for the provided id
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Response_model_nodata'
              examples:
                Example 1:
                  value:
                    time_stamp: '2019-08-24'
                    statusCode: 500
                    httpStatus: INTERNAL SERVER ERROR
                    message: An error occurred while updating resource
      operationId: put-resources-resource_id
      x-stoplight:
        id: ieysd181iq4gz
      description: Update data of a selected resource
      parameters:
        - schema:
            type: number
          in: query
          name: resource_id
          description: ID of the modified resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/Resource'
            examples:
              Example 1:
                value:
                  resource_id: 5
                  teacher_id: 7
                  total_resources: 5
                  used_resources: 1
                  study_year: 2024-2025
                  created_at: '2024-08-24'
components:
  schemas:
    Student:
      title: Student
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      x-stoplight:
        id: gsxk8mnrlx70k
      required:
        - student_id
        - student_name
        - email
      properties:
        student_id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 3en07d9q7zpv9
        student_name:
          type: string
          x-stoplight:
            id: rqzoabbgz4zfp
        email:
          type: string
          format: email
          x-stoplight:
            id: s7rjoejwlmwir
        class_code:
          type: string
          x-stoplight:
            id: t0nct9xt36qod
        created_at:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: v9gnhtumuo9bp
    Student_new:
      title: Student
      x-stoplight:
        id: yh2uw3adoqxms
      type: object
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      required:
        - student_name
        - email
      properties:
        student_name:
          type: string
          x-stoplight:
            id: cog4gi5fh51yb
        email:
          type: string
          format: email
        class_code:
          type: string
    Project:
      title: Project
      x-stoplight:
        id: 0adrtz89hl19x
      type: object
      required:
        - project_id
        - project_name
        - project_desc
        - company_id
        - project_status
        - start_date
      properties:
        project_id:
          type: number
          x-stoplight:
            id: 15869zlxnv9o5
        project_name:
          type: string
          x-stoplight:
            id: yd31h9nha6x5r
        project_desc:
          type: string
          x-stoplight:
            id: rrqikmbapwoj0
        teacher_id:
          type: number
          x-stoplight:
            id: 5l9cv4gqew9dc
        company_id:
          type: number
          x-stoplight:
            id: vscvguibn5jdh
        project_status:
          type: string
          x-stoplight:
            id: gf5svxx0uynrc
        project_url:
          type: string
          x-stoplight:
            id: 3h38ebpsfrhhr
          format: uri
        start_date:
          x-stoplight:
            id: 0efk7rbwkxz85
          type: string
          format: date
        end_date:
          type: string
          x-stoplight:
            id: rz6e7o545b2gu
          format: date
        created_at:
          type: string
          x-stoplight:
            id: ifx3g0bggyujg
          format: date
    Project_new:
      title: Project
      x-stoplight:
        id: bm53o54ir6bqv
      type: object
      required:
        - student_id
        - project_name
        - project_desc
        - company_id
        - project_status
        - start_date
      properties:
        student_id:
          type: number
        project_name:
          type: string
        project_desc:
          type: string
        teacher_id:
          type: number
        company_id:
          type: number
        project_status:
          type: string
        project_url:
          type: string
          format: uri
        start_date:
          type: string
          format: date
        end_date:
          type: string
          format: date
    Teacher_new:
      title: Teacher
      x-stoplight:
        id: fvbhi8v1sz99t
      type: object
      required:
        - teacher_name
        - email
      properties:
        teacher_name:
          type: string
        email:
          type: string
          format: email
    Resource:
      title: Resource
      x-stoplight:
        id: 539urmtoin9g9
      type: object
      required:
        - resource_id
        - teacher_id
        - total_resources
        - used_resources
        - study_year
      properties:
        resource_id:
          type: number
          x-stoplight:
            id: 9k6nhtfrruyal
        teacher_id:
          type: number
          x-stoplight:
            id: 68au46memeeeb
        total_resources:
          type: number
          x-stoplight:
            id: rzh5hilzlfz5s
        used_resources:
          type: number
          x-stoplight:
            id: tscnxzapkfw5g
        study_year:
          type: string
          x-stoplight:
            id: njyyxq23kpa2l
        created_at:
          type: string
          x-stoplight:
            id: kscrbt5nwxolo
          format: date
    Resource_new:
      title: Resource
      x-stoplight:
        id: yuv3j6qnfncsy
      type: object
      required:
        - teacher_id
        - total_resources
        - used_resources
        - study_year
      properties:
        teacher_id:
          type: number
        total_resources:
          type: number
        used_resources:
          type: number
        study_year:
          type: string
    Response_model_object:
      title: Response_model
      x-stoplight:
        id: e87e64u9l2dgy
      type: object
      properties:
        time_stamp:
          type: string
          format: date
        statusCode:
          type: number
        httpStatus:
          type: string
        message:
          type: string
        data:
          type: object
    Response_model:
      title: Response_model
      x-stoplight:
        id: ef6n5mso5230t
      type: object
      properties:
        time_stamp:
          type: string
          x-stoplight:
            id: 5bqfu9dp035dh
          format: date
        statusCode:
          type: number
          x-stoplight:
            id: hdvkk9jn4018b
        httpStatus:
          type: string
          x-stoplight:
            id: ejogptbv74dze
        message:
          type: string
          x-stoplight:
            id: cf3qcxufr8mbi
        data:
          type: array
          x-stoplight:
            id: k1yl7psja3ts2
          items:
            x-stoplight:
              id: wafjx3nhnlpcl
            type: object
    Response_model_nodata:
      title: Response_model
      x-stoplight:
        id: pzeqyjzxhbu1a
      type: object
      properties:
        time_stamp:
          type: string
          format: date
        statusCode:
          type: number
        httpStatus:
          type: string
        message:
          type: string
    Note_new:
      title: Note
      x-stoplight:
        id: rnfsatv7ifiwf
      type: object
      required:
        - note
        - created_by
      properties:
        note:
          type: string
        document_path:
          type: string
        created_by:
          type: string
      examples:
        - note: string
          document_path: string
          created_by: string
  requestBodies: {}
  responses: {}
